resources:
- ../../base
namePrefix: dev-

images:
- name: quay.io/jmaira/gitopsdemo
  newName: quay.io/jmaira/gitopsdemo
  newTag: 79a6246542e8f6236047ab2ba2288ed8eeccd82b

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "dev"
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "quay.io/jmaira/gitopsdemo:79a6246542e8f6236047ab2ba2288ed8eeccd82b"
  target:
    kind: Deployment
    name: my-app
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
