resources:
- ../../base
namePrefix: dev-

images:
- name: quay.io/jmaira/gitopsdemo
  newName: quay.io/jmaira/gitopsdemo
  newTag: f2730b6dbea6b62e4fb9047a10296bfd862f32da

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "dev"
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "quay.io/jmaira/gitopsdemo:f2730b6dbea6b62e4fb9047a10296bfd862f32da"
  target:
    kind: Deployment
    name: my-app
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
